# Generated by Django 3.2.9 on 2021-11-27 15:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0003_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='chronicles/'),
        ),
    ]
